version: '3.8'

services:

  kafka-message-scheduler:
    image: ${CONTAINER_REPOSITORY}/kafka-message-scheduler:latest<localBuild>
    depends_on:
      - kafka
      - zookeeper
    environment:
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9401
      OTEL_SERVICE_NAME: kafka-message-scheduler
      OTEL_INSTRUMENTATION_GRPC_ENABLED: 'false'
      OTEL_TRACES_EXPORTER: 'none'
      OTEL_LOGS_EXPORTER: 'none'
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: 'grpc'
      KAFKA_BROKERS: 'kafka:9092'
      KMS_LOGGING_LOGSTASH: 'true'
      KMS_LOGGING_LEVEL: INFO
      KMS_ROOT_LOGGING_LEVEL: INFO
      JAVA_TOOL_OPTIONS:
        -Dscheduler.topics.avro.0=avro-schedules
        -Dscheduler.topics.json.0=json-schedules
    ports:
      - "9401:9401"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT

  prometheus:
    image: prom/prometheus:v2.33.4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
