version: '3.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
    - "9093:9093"
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT

  kms:
    image: skyuk/kafka-message-scheduler:latest<localBuild>
    depends_on:
    - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEDULE_TOPICS: schedules
    ports:
    - "9095:9095"
