global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-message-scheduler'
    static_configs:
      - targets: ['kms:9095']
        labels:
          app_name: 'kafka-message-scheduler'
