global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kafka-message-scheduler'
    static_configs:
      - targets: ['kafka-message-scheduler:9401']
        labels:
          app_name: 'kafka-message-scheduler'
