addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.12.0")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.0")
addSbtPlugin("com.tapad"      % "sbt-docker-compose"  % "1.0.35")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"       % "0.1.8")
addSbtPlugin("com.github.sbt" % "sbt-dynver"          % "5.0.1")
addSbtPlugin("org.typelevel"  % "sbt-fs2-grpc"        % "2.7.14")
