addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-dynver"          % "5.1.1")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"       % "0.2.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.7")
addSbtPlugin("com.tapad"      % "sbt-docker-compose"  % "1.0.35")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.6.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.14.7")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.7")
