addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-release"         % "1.4.0")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"       % "0.1.8")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.tapad"      % "sbt-docker-compose"  % "1.0.35")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.4")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.14.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.2")
