version: '3.8'

services:

  kms:
    image: skyuk/kafka-message-scheduler:latest<localBuild>
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BROKERS: kafka:9092
      JAVA_TOOL_OPTIONS:
        -Dscheduler.reader.schedule-topics.0=schedules
        -Dscheduler.reader.schedule-topics.1=extraSchedules
    ports:
      - "9095:9095"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT

  prometheus:
    image: prom/prometheus:v2.33.4
    ports:
      - "9090:9090"
    volumes:
      - ../../docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
